{{- if .Values.schemaRegistry.mountedSecrets.enabled }}
{{- range $secret := .Values.schemaRegistry.mountedSecrets.secrets }}
  {{- if not $secret.dopplerEnabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret.name }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}