helmDefaults:
  verify: false
  wait: true
  force: false
  createNamespace: true
  cleanupOnFail: true

repositories:
- name: bitnami
  url: registry-1.docker.io/bitnamicharts
  oci: true

releases:
  - name: mysql
    chart: bitnami/mysql
    namespace: mysql
    version: 11.1.14
    createNamespace: true
    values:
      - ./values.yaml