connect:
  replicaCount: 1

  image:
    repository: debezium/connect
    pullPolicy: Always
    tag: "2.7"

  service:
    type: ClusterIP
    port: 8083
    protocol: TCP
    name: http

  autoscaling:
    enabled: false

  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

  env:
    - name: BOOTSTRAP_SERVERS
      value: kafka.kafka.svc.cluster.local:9092
    - name: GROUP_ID
      value: "1"
    - name: CONFIG_STORAGE_TOPIC
      value: debezium_connect_configs
    - name: OFFSET_STORAGE_TOPIC
      value: debezium_connect_offsets
    # - name: STATUS_STORAGE_TOPIC
    #   value: debezium_connect_statuses
    - name: KEY_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: VALUE_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONFIG_STORAGE_REPLICATION_FACTOR
      value: "1"
    - name: OFFSET_STORAGE_REPLICATION_FACTOR
      value: "1"
    - name: CONNECTOR_CLASS
      value: "io.debezium.connector.mysql.MySqlConnector"
    - name: DATABASE_HOSTNAME
      value: "mysql"
    - name: DATABASE_PORT
      value: "3306"
    - name: DATABASE_USER
      value: "root"
    - name: DATABASE_PASSWORD
      value: "root"
    - name: DATABASE_SERVER_ID
      value: "1"
    - name: DATABASE_SERVER_NAME
      value: "testing"
    # - name: TABLE_WHITELIST
    #   value: "mydatabase.mytable"
    - name: DATABASE_HISTORY_KAFKA_BOOTSTRAP_SERVERS
      value: "kafka.kafka.svc.cluster.local:9092"
    # - name: DATABASE_HISTORY_KAFKA_TOPIC
    #   value: "dbhistory.my-mysql-db"

ui:
  enabled: true
  replicaCount: 1

  image:
    repository: debezium/debezium-ui
    pullPolicy: Always
    tag: "2.5"

  service:
    type: ClusterIP
    port: 8080
    protocol: TCP
    name: http

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

  # env:
  #   - name: KAFKA_CONNECT_URIS
  #     value: "http://kconnect.confluent.svc.cluster.local:8083"
  #   - name: CONFIG_STORAGE_TOPIC
  #     value: debezium_connect_configs
  #   - name: OFFSET_STORAGE_TOPIC
  #     value: debezium_connect_offsets

