helmDefaults:
  verify: false
  wait: true
  force: false
  createNamespace: true
  cleanupOnFail: true

repositories:
- name: bitnami
  url: registry-1.docker.io/bitnamicharts
  oci: true

releases:
  - name: kafka
    chart: bitnami/kafka
    namespace: kafka
    version: 29.3.13
    createNamespace: true
    values:
      - ./values.yaml